export const REGISTER_CATTLE_REQUEST = "REGISTER_CATTLE_REQUEST";
export const REGISTER_CATTLE_SUCCESS = "REGISTER_CATTLE_SUCCESS";
export const REGISTER_CATTLE_FAIL = "REGISTER_CATTLE_FAIL";
export const REGISTER_CATTLE_RESET = "REGISTER_CATTLE_RESET";

export const ALL_CATTLE_REQUEST = "ALL_CATTLE_REQUEST";
export const ALL_CATTLE_SUCCESS = "ALL_CATTLE_SUCCESS";
export const ALL_CATTLE_FAIL = "ALL_CATTLE_FAIL";


export const DELETE_CATTLE_REQUEST = "DELETE_CATTLE_REQUEST";
export const DELETE_CATTLE_SUCCESS = "DELETE_CATTLE_SUCCESS";
export const DELETE_CATTLE_FAIL = "DELETE_CATTLE_FAIL";
export const DELETE_CATTLE_RESET = "DELETE_CATTLE_RESET";

export const UPDATE_CATTLE_REQUEST = "UPDATE_CATTLE_REQUEST";
export const UPDATE_CATTLE_SUCCESS = "UPDATE_CATTLE_SUCCESS";
export const UPDATE_CATTLE_FAIL = "UPDATE_CATTLE_FAIL";
export const UPDATE_CATTLE_RESET = "UPDATE_CATTLE_RESET";

export const CATTLE_DETAILS_REQUEST = "CATTLE_DETAILS_REQUEST";
export const CATTLE_DETAILS_SUCCESS = "CATTLE_DETAILS_SUCCESS";
export const CATTLE_DETAILS_FAIL = "CATTLE_DETAILS_FAIL";

export const DELETE_PRODUCT_RESET = "DELETE_PRODUCT_RESET";
export const UPDATE_PRODUCT_RESET = "UPDATE_PRODUCT_RESET";


export const CLEAR_ERRORS = 'CLEAR_ERRORS';