export const REGISTER_DOCTOR_REQUEST = "REGISTER_DOCTOR_REQUEST";
export const REGISTER_DOCTOR_SUCCESS = "REGISTER_DOCTOR_SUCCESS";
export const REGISTER_DOCTOR_FAIL = "REGISTER_DOCTOR_FAIL";
export const REGISTER_DOCTOR_RESET = "REGISTER_DOCTOR_RESET";

export const ALL_DOCTOR_REQUEST = "ALL_DOCTOR_REQUEST";
export const ALL_DOCTOR_SUCCESS = "ALL_DOCTOR_SUCCESS";
export const ALL_DOCTOR_FAIL = "ALL_DOCTOR_FAIL";

export const ASSIGN_CATTLE_REQUEST = "ASSIGN_CATTLE_REQUEST";
export const ASSIGN_CATTLE_SUCCESS = "ASSIGN_CATTLE_SUCCESS";
export const ASSIGN_CATTLE_FAIL = "ASSIGN_CATTLE_FAIL";
export const ASSIGN_CATTLE_RESET = "ASSIGN_CATTLE_RESET";


export const DELETE_DOCTOR_REQUEST = "DELETE_DOCTOR_REQUEST";
export const DELETE_DOCTOR_SUCCESS = "DELETE_DOCTOR_SUCCESS";
export const DELETE_DOCTOR_FAIL = "DELETE_DOCTOR_FAIL";
export const DELETE_DOCTOR_RESET = "DELETE_DOCTOR_RESET";

export const UPDATE_DOCTOR_REQUEST = "UPDATE_DOCTOR_REQUEST";
export const UPDATE_DOCTOR_SUCCESS = "UPDATE_DOCTOR_SUCCESS";
export const UPDATE_DOCTOR_FAIL = "UPDATE_DOCTOR_FAIL";
export const UPDATE_DOCTOR_RESET = "UPDATE_DOCTOR_RESET";

export const DOCTOR_DETAILS_REQUEST = "DOCTOR_DETAILS_REQUEST";
export const DOCTOR_DETAILS_SUCCESS = "DOCTOR_DETAILS_SUCCESS";
export const DOCTOR_DETAILS_FAIL = "DOCTOR_DETAILS_FAIL";


export const CLEAR_ERRORS = 'CLEAR_ERRORS';